#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-Pid
Version  : 1.01
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/C/CW/CWEST/File-Pid-1.01.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CW/CWEST/File-Pid-1.01.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfile-pid-perl/libfile-pid-perl_1.01-2.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-File-Pid-license
Requires: perl-File-Pid-man
Requires: perl(Class::Accessor::Fast)
BuildRequires : perl(Class::Accessor::Fast)

%description
NAME
File::Pid - Pid File Manipulation
SYNOPSIS
use File::Pid;

my $pidfile = File::Pid->new({
file => '/some/file.pid',
});

$pidfile->write;

if ( my $num = $pidfile->running ) {
die "Already running: $num\n";
}

%package license
Summary: license components for the perl-File-Pid package.
Group: Default

%description license
license components for the perl-File-Pid package.


%package man
Summary: man components for the perl-File-Pid package.
Group: Default

%description man
man components for the perl-File-Pid package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n File-Pid-1.01
mkdir -p %{_topdir}/BUILD/File-Pid-1.01/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/File-Pid-1.01/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-File-Pid
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-File-Pid/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/File/Pid.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-File-Pid/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/File::Pid.3
